# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/clock/clock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet

# IP: bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_clk_wiz_0_0 || ORIG_REF_NAME==clock_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/christian/Documents/CESE/Thesis/FreeRTOS-RISCV-PMP/E40S_PMP/RI5CY_UA.gen/sources_1/bd/clock/clock_ooc.xdc
