#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 03 17:36:35 CEST 2024
# SW Build 3900603 on Fri Jun 16 19:30:25 MDT 2023
#
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Zynq_E40S_PMP_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:Zynq_E40S_PMP_wrapper} -tclbatch Zynq_E40S_PMP_wrapper.tcl -protoinst "protoinst_files/Zynq_E40S_PMP.protoinst" -view /home/christian/Documents/CESE/Thesis/FreeRTOS-RISCV-PMP/E40S_PMP/ssp_tb_behav.wcfg -log simulate.log"
xsim Zynq_E40S_PMP_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:Zynq_E40S_PMP_wrapper} -tclbatch Zynq_E40S_PMP_wrapper.tcl -protoinst "protoinst_files/Zynq_E40S_PMP.protoinst" -view /home/christian/Documents/CESE/Thesis/FreeRTOS-RISCV-PMP/E40S_PMP/ssp_tb_behav.wcfg -log simulate.log

