#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 20 15:48:37 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ssp_tb_behav -key {Behavioral:sim_1:Functional:ssp_tb} -tclbatch ssp_tb.tcl -protoinst "protoinst_files/clock.protoinst" -view /home/christian/Documents/CESE/Thesis/FreeRTOS-RISCV-PMP/E40S_PMP/ssp_tb_behav.wcfg -log simulate.log"
xsim ssp_tb_behav -key {Behavioral:sim_1:Functional:ssp_tb} -tclbatch ssp_tb.tcl -protoinst "protoinst_files/clock.protoinst" -view /home/christian/Documents/CESE/Thesis/FreeRTOS-RISCV-PMP/E40S_PMP/ssp_tb_behav.wcfg -log simulate.log

